# Generated by Django 2.2.6 on 2019-12-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleSayac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='indMagazine',
            field=models.BooleanField(verbose_name='Indizado'),
        ),
    ]
