# Generated by Django 2.2.6 on 2020-02-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='Nombre(s)')),
                ('lastName', models.CharField(max_length=50, verbose_name='Apellido(s)')),
                ('emailAccount', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo UABC')),
                ('passwordAccount', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('confirmPasswordAccount', models.CharField(max_length=50, verbose_name='Confirmar Contraseña')),
            ],
        ),
    ]
