# Generated by Django 2.2.6 on 2019-11-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameMagazine', models.CharField(max_length=50, verbose_name='Nombre de revista')),
                ('referenceMagazine', models.CharField(max_length=100, verbose_name='Enlace a revista')),
            ],
        ),
    ]
