# Generated by Django 2.2.6 on 2019-12-06 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAcademy', models.CharField(max_length=100, verbose_name='Cuerpo académico')),
                ('codeAcademy', models.CharField(max_length=100, verbose_name='Clave')),
                ('createdPubAcademy', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProgram', models.CharField(max_length=100, verbose_name='Nombre de programa')),
                ('numberProgram', models.CharField(max_length=100, verbose_name='Código de programa')),
                ('respProgram', models.PositiveIntegerField(verbose_name='Responsable en proyectos')),
                ('partProgram', models.PositiveIntegerField(verbose_name='Participación en proyectos')),
                ('createdPubProgram', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberUser', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de empleado')),
                ('nameUser', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre completo')),
                ('estatusUser', models.CharField(choices=[(None, 'Selecciona estado'), ('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=25, verbose_name='Estatus')),
                ('emailUser', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo UABC')),
                ('rolUser', models.CharField(blank=True, choices=[(None, 'Selecciona estado'), ('Profesor/Investigador', 'Profesor/Investigador'), ('Técnico académico', 'Técnico académico'), ('Estudiante licenciatura', 'Estudiante licenciatura'), ('Estudiante postgrado', 'Estudiante postgrado')], max_length=25, null=True, verbose_name='Rol en UABC')),
                ('createdPubUser', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('academyUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userSayac.Academy', verbose_name='Cuerpo académico')),
                ('programUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userSayac.Program', verbose_name='Programa educativo')),
            ],
        ),
    ]
